{{- if .Values.schema.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: schema-{{ .Values.name }}
#  namespace: roboshop
  labels:
    appName: {{ .Values.name }}
spec:
  template:
    spec:
      containers:
        {{- range $item := .Values.schema.containers }}
        - name: {{ $item.name }}
          image: "public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load"
          env:
            {{- toYaml $.Values.schema.env | nindent 12 }}          
            - name: SCHEMA_FILE
              value: db/{{ $item.file }} 
        {{- end }}    
      restartPolicy: Never
  backoffLimit: 0 
{{- end -}}  